version: "3.9"

services:
  scylla-trade-repository:
    container_name: trade-repository
    image: scylladb/scylla:latest
    restart: always
    command: --seeds=scylla-trade-repository --smp 1 --memory 750M --overprovisioned 1 --api-address 127.0.0.1
    ports:
      - "9042:9042"
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
      - "./scylla/trade-repository.txt:/trade-repository.txt"
    networks:
      - web

  unlimited-order-book:
    build:
      context: ./
      dockerfile: Dockerfile 
    ports:
      - "8000:8000"
    networks:
      - web
    depends_on:
      - scylla-trade-repository

networks:
  web:
    driver: bridge
